### ISSUE TITLE
Project documentation updated (4/25) (4/26 re-update)

### ISSUE THREAD

**Issue by strikef** [snu-sf-class/swpp202401#41]
### Updates
* Add policy for minimum PRs merged per sprint
* Revise policy for maximum PRs merged per sprint
* Revise policy for adding existing LLVM passes
* Revise policy for compiling the project when running the test

Read through the [documentation](https://github.com/snu-sf-class/swpp202401/blob/main/project/project.pdf) for more details

**Comment by jjkim0309** [comment]
>     * Revise policy for adding existing LLVM passes

1. Does adding existing LLVM passes require a separate pull request for each pass?
2. if so, does each of these pull requests count towards a limit of 3 PRs?
